FF XrayWrapper fix
Error: Not allowed to define cross-origin object as property on [Object] or [Array] XrayWrapper

- we are cloning the object instead of using the fetched one